game.ReplicatedStorage.LoadoutPrimary:FireServer("MP5")
game.ReplicatedStorage.LoadoutPrimary:FireServer("MP5-SD")
game.ReplicatedStorage.LoadoutPrimary:FireServer("SPAS-12")
game.ReplicatedStorage.LoadoutPrimary:FireServer("M4A1")
game.ReplicatedStorage.LoadoutPrimary:FireServer("M4A1-SD")
game.ReplicatedStorage.LoadoutSecondary:FireServer("Glock 17")
game.ReplicatedStorage.LoadoutSecondary:FireServer("Glock 17-SD")
game.ReplicatedStorage.LoadoutSecondary:FireServer("Baretta 92FS")
game.ReplicatedStorage.LoadoutSecondary:FireServer("Glock 17-SD")
game.ReplicatedStorage.LoadoutMelee:FireServer("Black Mesa Personnel")
game.ReplicatedStorage.LoadoutMelee:FireServer("BMSF Personnel")
game.ReplicatedStorage.LoadoutMelee:FireServer("HECU Marines")
game.ReplicatedStorage.LoadoutMelee:FireServer("Black Ops Agents")
game.ReplicatedStorage.LoadoutMelee:FireServer("Headcrab Zombies")
game.ReplicatedStorage.LoadoutGP:FireServer("Crowbar")
game.ReplicatedStorage.LoadoutGP:FireServer("M249")
game.ReplicatedStorage.LoadoutGP:FireServer("Crossbow")
game.ReplicatedStorage.LoadoutGP:FireServer("M40A1")
game.ReplicatedStorage.LoadoutGP:FireServer("M21")
game.ReplicatedStorage.LoadoutGP:FireServer("Tau Cannon")
game.ReplicatedStorage.LoadoutGP:FireServer("Tau Hand Truck")
game.ReplicatedStorage.LoadoutGP:FireServer("Medicine Injector")
game.ReplicatedStorage.LoadoutGP:FireServer("Blow Torch")
game.ReplicatedStorage.LoadoutGP:FireServer("Dual G17s")
game.ReplicatedStorage.LoadoutGP:FireServer("MP5K")
game.ReplicatedStorage.LoadoutGP:FireServer("M240")
game.ReplicatedStorage.LoadoutGP:FireServer("M1014")
game.ReplicatedStorage.LoadoutGP:FireServer("Desert Eagle")
game.ReplicatedStorage.LoadoutGP:FireServer("Colt Python Elite")
